load('spatialData_NumData_1000.mat','distances_all');
voxel_distances=distances_all;
load('fitting_NumData_1000.mat','fitting_stat_all');
voxel_fitting=fitting_stat_all;
load('corrCoeff_distances_ontoDist_clean.mat','distances_clean');
structure_distances=distances_clean;
load('fitting_structures.mat','fitting_stat_all');
structure_fitting=fitting_stat_all;
%% exponential fit, old (structureUnionize) and new (voxel)
[~,F] = plotFitting_twoDataTypes(voxel_distances,...
                                  structure_distances,...
                                  'exp',...
                                  voxel_fitting, ...
                                  structure_fitting, ...
                                  'voxel', ...
                                  'structure')
str = fullfile('Outs','exponential_plot','voxel_structure_expFit.jpeg');
imwrite(F.cdata, str, 'jpeg');
