function [fitresult, gof] = createFit(distance_clean, corrCoeff_clean)
%CREATEFIT(DISTANCE_CLEAN,CORRCOEFF_CLEAN)
%  Create a fit.
%
%  Data for 'P28_expo1' fit:
%      X Input : distance_clean
%      Y Output: corrCoeff_clean
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Jun-2017 14:28:36


%% Fit: 'P28_expo1'.
[xData, yData] = prepareCurveData( distance_clean, corrCoeff_clean );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.372864516676737 -5.68109975689906e-05];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'P28_expo1' );
h = plot( fitresult, xData, yData );
legend( h, 'corrCoeff_clean vs. distance_clean', 'P28_expo1', 'Location', 'NorthEast' );
% Label axes
xlabel distance_clean
ylabel corrCoeff_clean
grid on


