function makeGeneExpressionMatrix_enrichedGenes(whatNorm,...
                                                whatVoxelThreshold,...
                                                whatGeneThreshold,...
                                                thisBrainDiv,...
                                                thisCellType) % both thresholds set to 0.3
%whatNorm='scaledSigmoid'; % normalizing method for makeGridData
%-------------------------------------------------------------------------------
% Create gene coexpression matrix
%-------------------------------------------------------------------------------
%%
% initialize
timePoints={'E11pt5','E13pt5','E15pt5','E18pt5','P4','P14','P28'};
% full size for 7 time points: 210000, 669369, 806520, 115240, 165550, 136000, 158629
% after filtering off spinal cord, unannotated voxels and only including forebrain,midbrain and hindbrain
% the number of voxels are (from voxelGeneCoexpression_all): 5031,9471,11314,11288,19754,21557,24826
% numData_brainDiv=[587,1000,1000,1000,1000,1000,1000]; % number of data ...
%for each time point when division of brain is under question...
%(instead of all brain)

% create gene coexpression matrix
for i=1:length(timePoints)
    [voxGeneMat,coOrds,propNanGenes,isGoodGene] = makeGridData_enrichedGenes(timePoints{i},...
                                                                            whatNorm,...
                                                                            whatVoxelThreshold,...
                                                                            whatGeneThreshold,...
                                                                            thisBrainDiv,...
                                                                            thisCellType);
    if strcmp(thisBrainDiv,'wholeBrain')
      str=fullfile('Matlab_variables', strcat('voxelGeneCoexpression_',thisCellType,'_',...
                  timePoints{i},'.mat'));
    else
      str=fullfile('Matlab_variables', strcat('voxelGeneCoexpression_',thisBrainDiv,'_',...
                    thisCellType,'_',timePoints{i},'.mat'));
    end
    save(str,'voxGeneMat','coOrds','propNanGenes','isGoodGene','-v7.3');
    clear voxGeneMat coOrds numNanGenes isGoodGene
end
end
