function makeConstantPlot(params,makeNewFigure,whatConstantOut,allGrey,...
                          linearRegress,showCorrCoeff,forceYLim,displayAdjR)


[xPlotDataAll,yPlotDataAll,numThresholds] = makeBinnedData(numData,...
                                                            numThresholds,...
                                                            thisBrainDiv,...
                                                            scaledDistance,...
                                                            thisCellType,...
                                                            thisDirection);
% Get max distances
numTimePoints = length(params.timePoints);
maxDistance = zeros(length(timePoints),1);
for i = 1:numTimePoints
    maxDistance(i) = getMaxDistance('wholeBrain',timePoints{i});
end

[fitting_stat_all, constantOut] = getFitting(xPlotDataAll,yPlotDataAll,whatConstantOut);

plotConstant(fitting_stat_all,constantOut,whatConstantOut,maxDistance,...
            thisBrainDiv,numData,numThresholds,makeNewFigure,...
            thisDirection,thisCellType,allGrey,linearRegress,...
            showCorrCoeff,forceYLim,displayAdjR);

end
