function makeConstantPlot(numData,numThresholds,thisBrainDiv,...
                          scaledDistance,thisCellType,thisDirection,...
                          makeNewFigure,whatConstantOut,allGrey,...
                          linearRegress,showCorrCoeff,forceYLim,displayAdjR)
% Plot decay constant against max distance
% numData=1000;
% numThresholds=20;
% thisBrainDiv='wholeBrain';
% scaledDistance=false;
% thisCellType='allCellTypes';
% thisDirection='allDirections';
% makeNewFigure = true;
% whatConstantOut = 'decayConstant';
% allGrey = false;
% linearRegress = true;
% showCorrCoeff = false;
% forceYLim = false;

timePoints = GiveMeParameter('timePoints');
resolutionGrid = GiveMeParameter('resolutionGrid');
constantTypes = GiveMeParameter('constantTypes');
maxDistance = zeros(length(timePoints),1);
[xPlotDataAll,yPlotDataAll,numThresholds] = makeBinnedData(numData,...
                                                            numThresholds,...
                                                            thisBrainDiv,...
                                                            scaledDistance,...
                                                            thisCellType,...
                                                            thisDirection);
% get max distance
for i=1:length(timePoints)
    fileName = sprintf('voxelGeneCoexpression_%s.mat',timePoints{i});
    load(fileName,'voxGeneMat','coOrds');
    maxDistance(i) = (max(coOrds(:,1))-min(coOrds(:,1)))*resolutionGrid.(timePoints{i});
end

if scaledDistance
    [fitting_stat_all,constantOut,~] = makeBinnedFitting(xPlotDataAll,...
                                                        yPlotDataAll,...
                                                        numThresholds,...
                                                        whatConstantOut);
    % Get the original (unscaled) max distance for plotting
    [xPlotDataAll,yPlotDataAll,numThresholds] = makeBinnedData(numData,...
                                                              numThresholds,...
                                                              thisBrainDiv,...
                                                              false,...
                                                              thisCellType,...
                                                              thisDirection);
    % Get max distance
    % [~,~,maxDistance] = makeBinnedFitting(xPlotDataAll,...
    %                                       yPlotDataAll,...
    %                                       numThresholds,...
    %                                       whatConstantOut);

else
    [fitting_stat_all,constantOut,~] = makeBinnedFitting(xPlotDataAll,...
                                            yPlotDataAll,...
                                            numThresholds,...
                                            whatConstantOut);
end

plotConstant(fitting_stat_all,constantOut,whatConstantOut,maxDistance,...
            thisBrainDiv,numData,numThresholds,makeNewFigure,...
            thisDirection,thisCellType,allGrey,linearRegress,...
            showCorrCoeff,forceYLim,displayAdjR);

end
