function makeBinnedFitting_enrichedGenes(numData,numThresholds,thisBrainDiv,...
                                          thisCellType,scaledDistance)
% initialize
timePoints={'E11pt5','E13pt5','E15pt5','E18pt5','P4','P14','P28'};

  if strcmp(thisBrainDiv,'wholeBrain')
    if scaledDistance
      filestr=strcat('binnedData_NumData_',num2str(numData),'_numThresholds_',...
                    num2str(numThresholds),'_',thisCellType,'_scaled');
    else
      filestr=strcat('binnedData_NumData_',num2str(numData),'_numThresholds_',...
                  num2str(numThresholds),'_',thisCellType);
    end
  else
    if scaledDistance
      filestr=strcat('binnedData_NumData_',num2str(numData),'_numThresholds_',...
                    num2str(numThresholds),'_',thisBrainDiv,'_',thisCellType,'_scaled');
    else
      filestr=strcat('binnedData_NumData_',num2str(numData),'_numThresholds_',...
                    num2str(numThresholds),'_',thisBrainDiv,'_',thisCellType);
    end
  end

load(strcat(filestr,'.mat'));
[fitting_stat_all, decayConstant, maxDistance]=getFitting(xPlotDataAll,yPlotDataAll);

if strcmp(thisBrainDiv,'wholeBrain')
  if scaledDistance
    str=fullfile('Matlab_variables',...
                  strcat('fitting_NumData_',num2str(numData),'_',...
                        'binnedData_numThresholds_',num2str(numThresholds),...
                        '_',thisCellType,'_scaled','.mat'));
  else
    str=fullfile('Matlab_variables',...
                  strcat('fitting_NumData_',num2str(numData),'_',...
                        'binnedData_numThresholds_',num2str(numThresholds),...
                        '_',thisCellType,'.mat'));
  end
else
  if scaledDistance
    str=fullfile('Matlab_variables',...
                strcat('fitting_NumData_',num2str(numData),'_',...
                      'binnedData_numThresholds_',num2str(numThresholds),'_',...
                      thisBrainDiv,'_',thisCellType,'_scaled','.mat'));
  else
    str=fullfile('Matlab_variables',...
                strcat('fitting_NumData_',num2str(numData),'_',...
                      'binnedData_numThresholds_',num2str(numThresholds),'_',...
                      thisBrainDiv,'_',thisCellType,'.mat'));
  end
end
save(str,'fitting_stat_all','decayConstant','maxDistance');
end
